###
GET http://localhost:3000/auth/publico

###
POST http://localhost:3000/auth/autenticado
Content-Type: application/json

{
    "email": "wilker@zenthall.com",
    "password": "test1234"
}

###
POST http://localhost:3000/auth/autorizado
Content-Type: application/json

{
    "email": "pablo@rodeology.com",
    "password": "test123"
}